AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for get-url-lambda

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to store the objects

Globals:
  Function:
    Timeout: 10

Resources:
  GetUrlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: get-url-lambda/
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 3      
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: AWS_IAM
        InvokeMode: BUFFERED
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Policies:
        - AWSLambdaBasicExecutionRole
        # S3 Policy to allow the function to read from the bucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:aws:s3:::${BucketName}/*

  # CloudFront Distribution with Lambda function URL as the origin with Origin and Behaviors configuration 
  # following best practices for a Lambda function URL origin.
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Select [2, !Split ["/", !GetAtt GetUrlFunctionUrl.FunctionUrl]] 
            Id: MyCFNToLambdaOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
              OriginKeepaliveTimeout: 60
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl  
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: MyCFNToLambdaOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachePolicyId: !Ref CachingDisabledPolicy
          ForwardedValues:
            QueryString: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2
        DefaultRootObject: index.html
        PriceClass: PriceClass_All

  # Permission to invoke the Lambda function from the CloudFront Distribution
  LambdaInvokePermissionForCloudFront:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetUrlFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "cloudfront.amazonaws.com"
      SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
      SourceAccount: !Sub "${AWS::AccountId}"

  # Origin Access Control to associate with the CloudFront Distribution    
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac-for-lambda-url" 
        SigningBehavior: always
        OriginAccessControlOriginType: lambda
        SigningProtocol: sigv4
  
  # Recommended cache policy to disable caching for the Lambda function URL origin
  CachingDisabledPolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-cache-policy"
        DefaultTTL: 0
        MinTTL: 0
        MaxTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

# Output values of created resources to be referenced in the calling stack
Outputs:
  CloudFrontDistributionId:
    Description: "The CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
  CloudFrontDomainName:
    Description: "The CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
  LambdaFunctionDomain:
    Description: Lambda Function URL domain.
    Value: !Select [2, !Split ["/", !GetAtt GetUrlFunctionUrl.FunctionUrl]]
  LambdaFunctionUrl:
    Description: "The Lambda Function URL"
    Value: !GetAtt GetUrlFunctionUrl.FunctionUrl
